# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='datamodel',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurer.Risk'),
        ),
    ]
